### ISSUE TITLE
[Rnd] research Flux project

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#177]
- https://github.com/fluxcd/flux2
- upstream project status (contributions, how much community engagement is around, etc.)
- deploy it, what components does it consist of, how do they interact
- airgap / HA deployment specifics
- deployments strategies (standalone vs hub)
- how does source reconcile works (how often, specifics, if manual reconcile is available)
- dependency management
- permissions / access control

**Comment by DinaBelova** [comment]
https://github.com/wahabmk/fun-with-fluxcd

**Comment by wahabmk** [comment]
##  Using Flux on Air-Gapped Environment

The [air-gapped](https://fluxcd.io/flux/installation/configuration/air-gapped/) document provides a good summary of how to get flux working on an airgapped environment.

One of the issues that people have faced is that the `source-controller` is unable to pull from a private registry (necessary for an air-gapped environment) due to `x509 unknown self-signed cert` errors, even if the required certs were placed in the host node's trust store (e.g. `/etc/ssl/certs`).

The reason for this is because the `source-controller` pod does not read/inherit the underlying host's trust store when starting up. The workaround is to patch the `source-controller` Deployment via kustomize to place the cert for the private registry in `/etc/ssl/certs` location of the pod. The following issue does a good job of showing how to do so using an init container: https://github.com/fluxcd/source-controller/issues/508.

### SIDENOTE
I have noticed that this is the typical approach with widely-used tools, where the tool does not inherit the system's cert pool for security reasons. We faced a similar issue in MSR when we enabled MSR's redirect option. This option basically used HTTP Temporary Redirect to tell the client making the pull request to download the artifacts (chart or blobs) from the actual source (e.g. S3 bucket) rather than going through MSR. This worked fine with Docker CLI, but failed with Helm CLI. Curiously, Helm even added another layer of SNI check on top of not inheriting the host's cert pool, which unfortunately causes inconvenience for no additional gain in security. Other projects (including `k0sproject`) working with registries have also faced this problem with helm. We reported the issue (https://github.com/helm/helm/issues/9317) to helm almost 3 years ago along with a fix (https://github.com/helm/helm/pull/9318), but it is still unmerged.

**Comment by wahabmk** [comment]
## High-Availability & Sharding of Flux Components
I have created the following for deploying Flux in a cluster in a Highly Available configuration. See the README for what is contained in the repository and how to deploy: 

https://github.com/wahabmk/fun-with-fluxcd/tree/sharding-example
