### ISSUE TITLE
E2e verification of VMware templates

### ISSUE THREAD

**Issue by DinaBelova** [Mirantis/hmc#254]

**Comment by a13x5** [comment]
@DinaBelova This tests couldn't be run on CI (our GH Actions), only manual runs will be possible at this point. 
The reason here is that vSphere is in private network, so the only solution will be to maintain our own GH Actions runner inside our internal network which has access to all internal resources.
I don't think it's possible right now. If it's required to run tests automatically it should be discussed separately.
